language: python
services:
  - docker
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update
  - sudo apt-get install -y zip swig cmake ninja-build libboost-dev
  - pip3 install scikit-build
  - python3 setup.py sdist -d docker-build
  - docker build -t siqad/siqadtools docker-build
  - docker ps -a
script:
  - docker run -u root --entrypoint=/bin/sh --rm -i -v ${TRAVIS_BUILD_DIR}/wheelhouse:/output
    siqad/siqadtools -c "ls; ls wheelhouse; cp wheelhouse/* /output; ls /output"
  - docker ps -a
  - zip -r wheelhouse.zip wheelhouse
deploy:
  provider: releases
  api_key:
    secure: o4z9VJ29PGyPK1LYxuINIXzGAEXIf58MT3ot9f2UoUhjAtIPOAPQXIMCkVq0N6XOSMAMsET++vhoiZ2RCvDzmSjGWHMVn9ow0tnUww+SbgM2x+o+RS9TGc0hM9qNzXX6FA7nvcqrvO1CjTDEbpyW5j3fIEJTwQrtzKNLvIKmOHxc6Yq/v/ei2lK1JSfo9HYqkkSFYHAUJZa2QmfCOyEqETzcKoUDSI0M6p0Sekc1kU/QHXr3lPkORy5tBCqerLDXBctsLCRuC6bNcOCgOhyWwj98wzeTTeZgzSMnI7x04HB67gPUrvP3vtnHElbn/UrsgLGl3hCzUHhsdSbfWVFa4rewclH6E/OWi6h0ylzRZSDpgLy6L8Rvvaczh4m+mAXYWaYp9jYsMW7dNKb0RJPOofYbsJfDBzh8aHlasVZOQoJkGkwQii+1hrwOwQ29ZNNOweD11mM9br5lSKHFgmKYJGf0CK6Z0PVZFrEsAL0cAVeiFRcm46HW0IxBrtG9eZrf7N0WQWbe9sjMCseCKdeGwI2JBNUjVP+d9vgBD1HDBTo+u8qrU5ABysFtegGYi4z8J+KXhvuAAWG0OLlXPBDk3UD22xjblElHUTCYCqQavnF+XAuOxhAg3iydV7Y8NB2xj7UFA5j0mgaWG1k3jmbMsRWUnCB8n1YeLiGCbHlFewQ=
  file: 'wheelhouse.zip'
  skip_cleanup: true
  draft: true
  on:
    repo: samuelngsh-testing/siqadconn
